### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by MokiMeow** [hardikverma22/travel-planner-ai#3] opened 2024-05-19 11:33 UTC
hey, noticed your project looks very good , wanted to know the env u used for this?
other than its a solid project , I would like something of putting a vid of some sort when it shows it comes up with a vid on the place

**Comment by hardikverma22** [comment] 2024-05-19 11:39
Hey,

Thanks for the feedback, but can you elaborate more about the vid part.
By the way, i have committed a sample env file but based on where the env variable is used i have placed them accordingly in my deployment, for example razorpay related vars are in vercel and openai related vars are in convex.

**Comment by MokiMeow** [comment] 2024-05-19 11:52
I thought it would be more engaging if the user sees a vid related to the place he goes so maybe when ever  a place is put for ex: lets take goa and the ai responds where to go , beside tht it would be better to add a link or a vid somewhere so the user gets engaged feels like to go there , so he understands where he is going and has better plan (ik this is vague but i thought would be useful) and i would also say to implement expenses so the ai could determine where all he can travel for the budget )

**Comment by hardikverma22** [comment] 2024-05-19 11:54
Sure, thanks, i will think about it and will try to find an api or something to get videos as well and host them on CDNs.

**Comment by MokiMeow** [comment] 2024-05-19 12:38
![Screenshot 2024-05-19 180705](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/4dde9b68-bf41-4dab-aeb8-a0f668ea138e)
hey wanted to know why cant i select the bar?

**Comment by hardikverma22** [comment] 2024-05-20 07:00
Thanks for notifying, I have fixed it now, the issue was caused by Clerk not sending the web hook for a new user.

**Comment by MokiMeow** [comment] 2024-05-20 08:27
Hey I have noticed some few more bugs in the mobile application when changed to dark mode it has a glitch and in dark mode the maps are not properly visible 
![IMG-20240520-WA0002](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/f58dc150-b847-4db2-bb9c-220294246af4)
![IMG-20240520-WA0001](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/069666e9-9b57-4722-81c6-07b3a564566e)

**Comment by hardikverma22** [comment] 2024-05-20 16:23
> ![WhatsApp Image 2024-05-20 at 15 33 43](https://private-user-images.githubusercontent.com/122464960/332024550-10017a4a-e06d-4be1-9c2d-31c6013b47c2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTk4OTUsIm5iZiI6MTcxNjE5OTU5NSwicGF0aCI6Ii8xMjI0NjQ5NjAvMzMyMDI0NTUwLTEwMDE3YTRhLWUwNmQtNGJlMS05YzJkLTMxYzYwMTNiNDdjMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTAwNjM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ4YjZkMGY3MTE0OGQxOTRkNDEzNmQyNTFjNmNlN2NjMDUwNjlmOTBjM2FmNDY1YjEwNDgwODAzZWI5N2FhMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.TEQvln7AkLi4Ijic0vjqU8fTSLvn00tHRP1vy_nvPGg) thanks for the above help, but I am stuck here , I have added my openai key, covex , clerk , still i can cant access that and i got 0 credits , at the start it should have 1 credit but it shows 0 credits whenever i load the page ? could u help with the issue

You should have the convex setup and up and running using the command **pnpm dlx convex dev --tail-logs**

**Comment by hardikverma22** [comment] 2024-05-20 16:23
> Hey I have noticed some few more bugs in the mobile application when changed to dark mode it has a glitch and in dark mode the maps are not properly visible , and in dark mode the application doesn't work sometimes ![IMG-20240520-WA0002](https://private-user-images.githubusercontent.com/122464960/331996071-f58dc150-b847-4db2-bb9c-220294246af4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTM5OTMsIm5iZiI6MTcxNjE5MzY5MywicGF0aCI6Ii8xMjI0NjQ5NjAvMzMxOTk2MDcxLWY1OGRjMTUwLWI4NDctNGRiMi1iYjljLTIyMDI5NDI0NmFmNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODI4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YjRjMDRlYjRkZGU5MWViMmQyZDNjZTViOTZmMTljZGFmZjI2ZTM5NTJjM2E2N2JmNDFiN2I5ZGVjMGU1M2EwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hHvWzUgMJqcmRA5AscqCBmoKqdNeu9Ar4fFKp4E4fdI) ![IMG-20240520-WA0001](https://private-user-images.githubusercontent.com/122464960/331996120-069666e9-9b57-4722-81c6-07b3a564566e.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTM5OTMsIm5iZiI6MTcxNjE5MzY5MywicGF0aCI6Ii8xMjI0NjQ5NjAvMzMxOTk2MTIwLTA2OTY2NmU5LTliNTctNDcyMi04MWM2LTA3YjNhNTY0NTY2ZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwODI4MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZTgyYjJiMDA0YmQ4ODVhZjJhZjAxODg1M2U5OTFjYjJlYzg3OWFkZWE3NzcwYWRkZTBlNjhiMjA2ZDcxZTBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.39_hjsSoS4VaFUJYGliU_twq3T9AKWO5oJPBpZbt-Y4)

Fixed the issue with Side drawer but maps dark mode is from google.

**Closed as completed by hardikverma22** 2024-05-20 16:23 UTC
Labels: enhancement

**Comment by MokiMeow** [comment] 2024-05-20 16:55
I
![WhatsApp Image 2024-05-20 at 22 19 56](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/e95e6cbf-dbd0-4b10-af8b-9887172b3ad6)
![WhatsApp Image 2024-05-20 at 22 19 55](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/bf40f95d-23a0-4724-b3b3-e4d327abcfde)
![WhatsApp Image 2024-05-20 at 22 19 56 (1)](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/51c7b34d-99fa-4478-988f-9749756d3909)
 completely have set up my convex and did run all but yet its not working , only the top 4 env I have set up with openai , not setup the clerk webhook (is it needed?) other than that I have completed necessary requirements , should I add anything in convex?, in the code somewhere I missed any key u reckon?

**Comment by hardikverma22** [comment] 2024-05-20 16:57
> I ![WhatsApp Image 2024-05-20 at 22 19 56](https://private-user-images.githubusercontent.com/122464960/332140626-e95e6cbf-dbd0-4b10-af8b-9887172b3ad6.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjQ0ODksIm5iZiI6MTcxNjIyNDE4OSwicGF0aCI6Ii8xMjI0NjQ5NjAvMzMyMTQwNjI2LWU5NWU2Y2JmLWRiZDAtNGIxMC1hZjhiLTk4ODcxNzJiM2FkNi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTY1NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWM0NTFmYTU1ZDZlYWYyYWY1NzdmNWZiNTk2ZjI4MjUzOTFiYWRlMTFiNzU1YWVkZmU3NTMyMTAwNDdkNjE3NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.f2UiaeUpw1Rlb5qH-nLxynlcly0D27jmf8dwvJPvxpE) ![WhatsApp Image 2024-05-20 at 22 19 55](https://private-user-images.githubusercontent.com/122464960/332140635-bf40f95d-23a0-4724-b3b3-e4d327abcfde.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjQ0ODksIm5iZiI6MTcxNjIyNDE4OSwicGF0aCI6Ii8xMjI0NjQ5NjAvMzMyMTQwNjM1LWJmNDBmOTVkLTIzYTAtNDcyNC1iM2IzLWU0ZDMyN2FiY2ZkZS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTY1NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTk5Y2MxYjk1MmZlYTIxM2JkZWQxMWM0NmY0ZjBjZGEzNjYwZTNjMGUxNDlkZGU1NzI0YTNlYWUzOTMxNWM5NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Oy3v_SbLiLFNW-NBL-RzWtjGuT2cG7mNOfDQ2-oefIg) ![WhatsApp Image 2024-05-20 at 22 19 56 (1)](https://private-user-images.githubusercontent.com/122464960/332140641-51c7b34d-99fa-4478-988f-9749756d3909.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMjQ0ODksIm5iZiI6MTcxNjIyNDE4OSwicGF0aCI6Ii8xMjI0NjQ5NjAvMzMyMTQwNjQxLTUxYzdiMzRkLTk5ZmEtNDQ3OC05ODhmLTk3NDk3NTZkMzkwOS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjBUMTY1NjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjljYzM0ZDUxNzYyY2M4N2Q4YTFhOWJlNGUyMzg0OGVhMjM5MTBhMDcwOWUxOWY4NGQ5OTg0MTA0MjU3YjhkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.mtDFLjTq5aPYHRVb93ZeeHVcgl97MytjZdR1-rr8_cY) completely have set up my convex and did run all but yet its not working , only the top 4 env I have set up with openai , not setup the clerk webhook (is it needed?) other than that I have completed necessary requirements , should I add anything in convex?, in the code somewhere I missed any key u reckon?

User should have been received from clerk webhook, that only adds a user in your convex db along with 1 credit without that nothing would work

**Comment by MokiMeow** [comment] 2024-05-20 18:23
![Screenshot 2024-05-20 234803](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/6124d9dd-2fe6-497d-948f-96d426a42eb2)
![WhatsApp Image 2024-05-20 at 23 50 28](https://github.com/hardikverma22/travel-planner-ai/assets/122464960/e5293ec4-e801-4a39-9869-1ebd8bae6687)
 i just completed setting up the webhook took long time but after I did it doesn't display if its success or fail and still its same, did i do anything wrong in the set up , in a vid I saw for the webhooks he used (/api) in the URL of the endpoint I didn't , was that  the issue?
